### PR TITLE
support using external webpack.config.js.

### PR DESCRIPTION
**Pull request by jaredlam**
[https://github.com/weexteam/weex-toolkit/issues/269](url)

Support using project's webpack.config.js, by execute:
```
 $ weex compile src dist -x
```
or
```
 $ weex compile src dist --external-webpack
```

### CODE REVIEW

**Comment by jaredlam** [comment]
{weexteam}/{weex-toolkit}#{269}

**Comment by jaredlam** [comment]
#11

**Comment by jaredlam** [comment]
#11

**Comment by jaredlam** [comment]
#https://github.com/weexteam/weex-toolkit/issues/269

**Comment by erha19** [comment]
@jaredlam you can use `weex compile src dist --config webpack.config.js` to compile with your local `webpack` config now and this pull request will be close later.

**Pull request closed without merging**
